name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  transparent_image: ^2.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  image_picker: ^1.1.2
  stomp_dart_client: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/svg/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"